repository: tomjoht/documentation-theme-jekyll
output: web
topnav_title: COVID Java Data Library
site_title: Docs - COVID Data Library
company_name: Alex Webber
github_editme_path: webber512/covid-data-library
google_analytics: null
host: 127.0.0.1
port: 4000
exclude:
- .idea/
- .gitignore
- vendor
feedback_subject_line: COVID Data Library
feedback_email: awwebber12@gmail.com
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
collections:
  tooltips:
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    comments: false
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    layout: page
    search: true
    tooltip: true
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    search: true
    sidebar: home_sidebar
    topnav: topnav
sidebars:
- home_sidebar
- mydoc_sidebar
- other
description: Documentation home for the COVID Data Library, a Java wrapper for accessing data from The Covid Tracking Project.
github:
- metadata